const { chromium } = require(process.env.CEYU_NODE_MODULES ? process.env.CEYU_NODE_MODULES + '/playwright' : 'playwright');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const {pathToFileURL} = require('node:url');
let browser;
(async () => {
  browser = await chromium.launch({headless:true,channel:'msedge'});
  const errors=[];
  const page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});
  page.on('pageerror',e=>errors.push(e.message));
  const url=pathToFileURL(path.resolve('app/src/main/assets/index.html')).href;
  await page.goto(url);
  await page.getByRole('heading',{name:'对话工作台'}).waitFor();
  await page.locator('[data-action=sample]').click();
  await page.getByRole('heading',{name:'留一点余地'}).waitFor();
  await page.locator('details.evidence').click();
  assert.match(await page.locator('details.evidence').innerText(),/不能|不足|可能/);
  fs.mkdirSync('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
  await page.locator('[data-action=helpful]').click();
  assert(await page.locator('[data-action=helpful]').evaluate(el=>el.classList.contains('active')));
  await page.locator('[data-action=unhelpful]').click();
  await page.locator('[data-value="语气不合适"]').click();
  assert(await page.locator('[data-action=unhelpful]').evaluate(el=>el.classList.contains('active')));
  await page.locator('#desktop-nav a[href="#people"]').click();
  await page.getByRole('heading',{name:'还没有人物档案'}).waitFor();
  await page.locator('#search-people').fill('<script>alert(1)</script>');
  await page.getByRole('heading',{name:'没有找到这个人'}).waitFor();
  await page.locator('#desktop-nav a[href="#settings"]').click();
  await page.locator('#endpoint').fill('http://insecure.example');
  await page.locator('[data-action=save-settings]').click();
  await page.getByRole('alert').filter({hasText:'HTTPS'}).waitFor();
  await page.locator('[data-action=export]').click();
  await page.locator('#backup-password').fill('short');
  await page.locator('[data-action=do-export]').click();
  assert(await page.locator('#modal').evaluate(el=>el.open));
  await page.locator('[data-action=close-modal]').first().click();
  await page.locator('[data-action=delete-all]').click();
  assert(await page.locator('#modal').innerText().then(t=>t.includes('无法撤销')));
  await page.locator('[data-action=close-modal]').first().click();
  for(const width of [360,412,768]){
    await page.setViewportSize({width,height:915});
    await page.goto(url);
    await page.locator('[data-action=sample]').click();
    await page.getByRole('heading',{name:'留一点余地'}).waitFor();
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`Overflow at ${width}`);
    if(width===412)await page.screenshot({path:'artifacts/mobile-result.png',fullPage:true});
    await page.locator('[data-action=mobile-input]').click();
    await page.locator('#chat-title').fill('很长的昵称LongUnbrokenIdentifier01234567890123456789');
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    if(width===412)await page.screenshot({path:'artifacts/mobile-input.png',fullPage:true});
    await page.locator('#mobile-nav a[href="#settings"]').click();
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  }
  await page.goto(url);
  await page.evaluate(()=>window.receiveState({native:false,text:'<img src=x onerror="window.pwned=true">',background:'',title:'<script>test</script>',goal:'自然延续',tone:'自然',personId:'',result:{action:'<script>window.pwned=true</script>',interpretation:'<img src=x onerror="window.pwned=true">',replies:[],memoryCandidates:[]},busy:false,silent:false,paused:false,capturing:false,error:'',notice:'',feedback:'',people:[],records:[],settings:{endpoint:'https://example.com',model:'model',keyConfigured:false,duration:3,handleY:.82,channel:'text',silentSave:false}}));
  assert.equal(await page.evaluate(()=>window.pwned),undefined);
  assert.equal(await page.locator('.next-step img').count(),0);
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('PASS: desktop/mobile layouts, navigation, feedback, validation, dialogs and untrusted-text rendering.');
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
